env:
  BUILD_TIMEOUT: 120
  TEST_TIMEOUT: 60
  TIMEOUT: 120
  VERBOSE: true

steps:

  - label: ":webhook: Trigger Travis CI Build"
    command: |
      . ./.cicd/travis-trigger.sh
    agents:
      queue: "automation-eos-builder-fleet"

  - trigger: "eos-vm-base-images-beta"
    label: ":docker: Ensure base images exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":ubuntu: [Ubuntu] 18.04 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eos-vm-ubuntu-18.04-910b4e4a97a4ee8d45f304528d536d9c4425238a"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18