env:
  BUILD_TIMEOUT: 120
  TEST_TIMEOUT: 60
  TIMEOUT: 120
  VERBOSE: true

steps:

  - label: ":webhook: Trigger Travis CI Build"
    command:
      - ". ./travis-trigger.sh"
    agents:
      queue: "automation-basic-builder-fleet"

  - trigger: "eos-vm-base-images-beta"
    label: ":docker: Ensure base images exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":ubuntu: [Ubuntu] 18.04 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eos-vm-ubuntu-18.04-8c69e80af565dc124d8218693ea7a548ca9dd359"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18